### PR TITLE
Storage functionalities

### PR DESCRIPTION
**Pull request by angu**
Added Storage functionalities so we can load a NN from a file.
I've not used the NSCoding protocol to avoid the @objc directive.
ActivationFunction now is of type String, we could also use Int

### CODE REVIEW

**Comment by vittoriom** [comment]
Is `Storage` declared twice? 

Also:
- in `getFileURL` there is a force unwrap that is maybe avoidable, since the function doesn't throw
- `write` and `read` use strings to store and retrieve stuff to and from a dictionary, maybe we could use an enum to avoid typos
- also I'm not for having serialization/deserialization code together with the definition of a class, but

anyway I'm not the maintainer of this repo, I'm just watching it with interest :D 
Handy way to store/load FFNNs from files!

**Comment by angu** [comment]
You are right about the getFileURL (it's just a convenience method for testing purpose, we can remove that).
I got the idea from OpenCV, they are doing something similar with the FileStorage thing

**Comment by collinhundley** [comment]
This is a good way to quickly load/save a neural network - I've merged it in.  A couple changes though:  I've added the ability to read/write using an `NSURL` in addition to `String`, in case the developer wishes to store the file in another location besides the Documents directory.  I've also renamed `ItemType` to `StorageType` to avoid ambiguity.

I question whether a `Storage` protocol is the best way to go, though.  Generally I would say yes, but I would like to keep each class in Swift AI as independent as possible.  This way, developers may import only the classes they need into their projects instead of the entire Swift AI module.  There are many more features coming besides this simple feed-forward network, so it remains to be seen what is the best way to maintain dependencies between files (or if we can avoid it entirely).

What are your thoughts?

**Comment by angu** [comment]
I thought about a protocol so the way to store/load NN or any component will be the same over the entire library. (Benefits: I know how to save a NN I also know how to save a SVM)
Have you ever thought about cocoapods or something similar? A solution could be to split the lib in core and submodules

**Comment by collinhundley** [comment]
I agree with your logic about the protocol.  The reason for avoiding cocoapods (for now) is to keep Swift AI platform-agnostic.  Until this particular merge, FFNN only used Apple's frameworks for a small number of calculations, which would be relatively simple to port to Linux when it becomes available.  However, the ability to read/write files has added another dependency on Foundation that I hope to remove eventually.

This introduces a dilemma: is it better to cater to Apple's platforms, or target a larger audience?  Linux-compatible code may benefit more people, but result in a loss of convenience for iOS developers.

**Comment by angu** [comment]
If your goal is to keep the cose as more platform-agnostic as possible we can do that.
We store the NN as an xml / some custom format and write using fopen etc.
I prefer target Apple's platform, but is just personal taste, and in the end is your call :)

**Comment by collinhundley** [comment]
For now, we'll stick with Foundation until Swift open-sources.  We'll have more information about what to expect within a month or so.

**Pull request merged**
