### PR TITLE
Avoid dispatching in loops

### PR DESCRIPTION
**Pull request by mipstian**
Fixes a TODO, and as you can imagine increases performance dramatically.

### CODE REVIEW

**Comment by mipstian** [comment]
Actually hold on a sec, I wanna make another small change

**Comment by mipstian** [comment]
All done :)

**Comment by collinhundley** [comment]
I'll pull this down and check it out - originally it was written similar to the way you've done it, but although it improved performance on the iOS Simulator, it didn't look as smooth on actual devices (apparently iPhones are much better at dispatching quickly). I'll merge as soon as I can verify that it looks ok.

**Comment by mipstian** [comment]
Fwiw it works fine on my iPhone 6.

I was worried that the network queue would swamp the main queue, but it seems to be fine. Alternatively we can dispatch_sync to the main queue when updating, which will slow down training overall, but make sure one the network queue doesn't run ahead. Your call.

**Comment by collinhundley** [comment]
You're building in Release mode, right? I'm getting quite a bit of jitter in the graph, although I'm not sure why. Dispatching asynchronously is allowing the network to get ahead of the UI for me - dispatch_sync fixes that problem but the jitter stays. I'm sure it depends on hardware, but it's happening on my 2015 rMBP Simulator and my iPhone 6.

**Comment by mipstian** [comment]
Good catch. Last commit I pushed should fix both issues. I didn't realize the points were `CALayer`s (and as such had implicit animations on). It's even faster now :)

**Comment by collinhundley** [comment]
Ah, good catch on the implicit animations!  It's much better now.

P.S. - does your simulator lock up when you move the slider while the network is training?  Mine freezes almost every time - not the app, but the actual iOS Simulator itself. Works fine on a real iPhone though - it might just be my installation.

**Comment by mipstian** [comment]
No, sim seems fine here, no freezes.

I have a question! Many time I see the network stabilizing in a configuration like this:
screen shot 2015-12-08 at 4 39 51 am
It seems to learn most of the curve almost instantly, but often it takes a while for it to learn the leftmost part, or it never does and looks like the screenshot above. And it's always the leftmost part! My understanding of the underlying math isn't good enough for me to even formulate an hypothesis... Any idea why this happens?

**Comment by collinhundley** [comment]
That's a good question... in fact, you've just pointed out an oversight on my part.

You've probably noticed that the neural net learns very quickly near the origin, and more slowly as you approach the left or right side of the graph.  This has to do with the nature of the sigmoid activation function:

Sigmoid

To put it simply, a neuron is able to "learn" more quickly when the derivative of its activation function has a higher magnitude - so, in the case of the sigmoid function, when the sum of the neuron's inputs is close to zero.

Because of this property, the sine wave regression "learns" more slowly at its extremes.  Looking back on the code, I made the mistake of updating the neural network with the actual displayed `x` values, when I actually intended to scale them first.  Look at the sigmoid: near `-5` and `5` the graph is nearly flat, which means that the network is learning extremely slowly for those values.  But if we were to scale the `x` values down to the domain `[-1, 1]` first, we should see much better performance (because we maintain a fairly high derivative for all inputs).  This is a change I will make soon.

As far as the left side getting stuck more often than the right, I can't think of any mathematical reason why that would be the case.  In my experience both sides are getting stuck fairly frequently.

**Comment by mipstian** [comment]
Got it, thanks for taking the time to explain that!

**Pull request merged**
