### PR TITLE
Add Phase shift to iOS Example

### PR DESCRIPTION
**Pull request by perlfly**
User can also play _shifting_ the sine function.
Shifting the sine function maintains the same _variance_ for the target function, while changing sine frequency also changes the target function variance.

Adaptation to phase shift can be seen as example of adaptation to the same _concept_ moving around.
Ex: a moving target inside a sequence of images

### CODE REVIEW

**Comment by collinhundley** [comment]
Very cool. The constraints will need to be modified for the iPhone 5/s, but other than that everything looks good!

**Comment by perlfly** [comment]
Gosh ... even worse on 4s. 
Am I wrong or at the moment the view containing the graph is not safely scalable?
I'd move the curve and _ball points_ placement to the GraphView since it is presentation logic. The controller will pass the curve and _ball points_ arrays to the GraphView for presentation.

Is there some doc about the layout functions used?

**Comment by collinhundley** [comment]
Currently the app isn't compatible with iPhone 4s and that's okay... the [docs](https://github.com/collinhundley/Swift-AI/tree/master/Examples) mention that only iPhone 5+ is supported, and the A5 processor is too slow to do much anyway. Eventually I'll make it fit on the 4s, but it's a low priority. Also - I'd rather keep the graph the way it is currently, but I've updated the sliders to fit better now.

As far as updating the view: all logic remains in the view controller, and the view contains purely layout code.  This is Apple's recommended pattern, and it conforms well with MVC architecture.  Think about it it this way:  the UIView subclass is the equivalent of a .XIB interface builder file. It defines subviews, constraints, frames, fonts, colors, etc., but performs no logic itself - this is left to its "controller."  The only difference is that the UIView is written in Swift (and subsequently allows you to debug issues), whereas a .XIB is stored in XML.

The views depend heavily on APKit - a framework written by myself and a colleague.  It might look strange to an outsider, but it saves countless hours of writing boilerplate layout/animation code.  It's very reliable, but unfortunately I have no documentation to provide right now.  We'll be open-sourcing APKit soon though, and documentation to go with it.  Until then - feel free to use my own code as a template!

**Comment by perlfly** [comment]
Fine so I can focus on the FFNN code ;-)

**Pull request merged**
